apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-playground
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      run: kube-playground
  template:
    metadata:
      labels:
        run: kube-playground
    spec:
      containers:
      - name: kube-playground
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080