apiVersion: v1
kind: Service
metadata:
  name: kube-playground
  labels:
    run: kube-playground
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    run: kube-playground
